#!/usr/bin/env bash
# Installs Nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx start
