#!/usr/bin/env bash
# Installs nginx web server and redirection

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$replace/" /etc/nginx/sites-enabled/default
sudo service nginx restart
