#!/usr/bin/env bash
# Installs nginx web server and redirection

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$replace/" /etc/nginx/sites-enabled/default
#create an error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/err404.html
replace="listen 80 default_server;\n\terror_page 404 \/err404.html;\n\tlocation = \/err404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$replace/" /etc/nginx/sites-enabled/default
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
