#!/usr/bin/env bash
# Install the load balanecer

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy=2.4.\*

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/original.cfg

echo "
frontend front
        bind *:80
        default_backend back
backend back
        balance roundrobin
        server 383178-web-01 54.167.183.135:80 check
        server 383178-web-02 100.25.17.178:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
